name: Unity CI (2022.3.26f1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1) Linux Mono 환경에서 PlayMode 테스트
  test-linux:
    name: PlayMode Tests (Linux Mono)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2.0.0
        with:
          unityVersion: 2022.3.26f1
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Run PlayMode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          testMode: playmode
          unityVersion: 2022.3.26f1

  # 2) Windows VM에서 Standalone Windows 빌드
  build-windows:
    name: Build Windows (Standalone)
    runs-on: windows-latest
    needs: test-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Build Windows
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.26f1
          targetPlatform: StandaloneWindows64
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
