# .github/workflows/windows-ci.yml
name: Windows CI (Unity 2022.3.26f1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-ci:
    name: Windows CI
    runs-on: windows-latest
    env:
      UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Run PlayMode Tests
        shell: pwsh
        run: |
          # Unity Hub가 설치된 기본 경로에서 2022.3.26f1 에디터 실행
          $unityPath = "C:\Program Files\Unity\Hub\Editor\2022.3.26f1\Editor\Unity.exe"
          & $unityPath -batchmode -projectPath $Env:GITHUB_WORKSPACE `
                        -runTests -testPlatform PlayMode `
                        -testResults "$Env:GITHUB_WORKSPACE\TestResults.xml" `
                        -logFile -
          # 테스트 결과 업로드용
      - name: Upload PlayMode Test Results
        uses: actions/upload-artifact@v3
        with:
          name: PlayMode-TestResults
          path: TestResults.xml

      - name: Build Windows Standalone
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion:       2022.3.26f1
          targetPlatform:     StandaloneWindows64
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Build
          path: build/Windows
