name: Unity Docker CI (2022.3.26f1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ─────────────────────────────────────────────
  # 1) PlayMode Tests in Docker (windows-mono)
  # ─────────────────────────────────────────────
  test:
    name: PlayMode Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write Unity license file
        run: |
          echo "${{ secrets.UNITY_LICENSE }}" > project.ulf

      - name: Pull Unity Docker image
        run: docker pull unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1

      - name: Run PlayMode Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -v ${{ github.workspace }}/project.ulf:/root/.local/share/unity3d/Unity_lic.ulf \
            unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1 \
            /opt/unity/Editor/Unity \
              -batchmode \
              -projectPath /project \
              -runTests \
              -testPlatform PlayMode \
              -testResults /project/TestResults.xml \
              -quit \
          && echo "Tests passed"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode-TestResults
          path: TestResults.xml

  # ─────────────────────────────────────────────
  # 2) Build Standalone Windows in Docker (same image)
  # ─────────────────────────────────────────────
  build:
    name: Build Windows
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write Unity license file
        run: |
          echo "${{ secrets.UNITY_LICENSE }}" > project.ulf

      - name: Pull Unity Docker image
        run: docker pull unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1

      - name: Build Windows Standalone
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -v ${{ github.workspace }}/project.ulf:/root/.local/share/unity3d/Unity_lic.ulf \
            unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1 \
            /opt/unity/Editor/Unity \
              -batchmode \
              -projectPath /project \
              -buildWindows64Player /project/build/Windows/Game.exe \
              -quit

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/Windows
