name: Unity CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1) 코드 체크아웃
      - uses: actions/checkout@v3

      # 2) 캐시 활용 (Library 폴더)
      - uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      # 3) 라이선스 활성화 (Pro 에디션이시면 UNITY_SERIAL 추가)
      - name: Activate Unity License
        uses: game-ci/unity-activate@v2.0.0
        with:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}  # Pro 라이선스가 없다면 생략
          unityVersion: auto

      # 4) PlayMode 테스트 실행
      - name: PlayMode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          testMode: playmode

      # 5) Windows용 빌드
      - name: Build Windows
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64
