# .github/workflows/unity-ci.yml
name: Unity CI (2022.3.26f1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1) PlayMode Tests on Ubuntu with windows‑mono Docker image
  test:
    name: PlayMode Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Run PlayMode Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath:     .
          githubToken:     ${{ secrets.GITHUB_TOKEN }}
          unityVersion:    2022.3.26f1
          customImage:     unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1  
          # windows‑mono 이미지는 linux/amd64 환경에서 실행 가능한 Docker 이미지입니다 :contentReference[oaicite:0]{index=0}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode-TestResults
          path: artifacts

  # 2) Build Standalone Windows on a Windows VM
  build:
    name: Build Windows
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Build Windows Standalone
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion:    2022.3.26f1
          targetPlatform:  StandaloneWindows64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/Windows
