name: Unity CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # (선택) 캐시 – 빌드 속도 최적화
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Build Windows
        uses: game-ci/unity-builder@v4
        env:
          # secrets에 미리 올려둔 .ulf 파일 내용
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # (Pro/Plus 라이선스일 경우)
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          unityVersion: 2022.3.26f1
          targetPlatform: StandaloneWindows64
