name: Unity CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: game-ci/unity-actions@v2
        with:
          version: 2022.3.26f1
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: game-ci/unity-actions@v2
        with:
          version: 2022.3.26f1
      - uses: game-ci/unity-test-runner@v2
        with:
          testMode: playmode
