# .github/workflows/unity-ci.yml
name: Unity CI (2022.3.26f1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1) PlayMode 테스트 (Docker + Windows‑Mono 이미지)
  test:
    name: PlayMode Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Run PlayMode Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath:  .
          githubToken:  ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2022.3.26f1
          testMode:     playmode
          # linux‑il2cpp 이미지가 없으니 windows‑mono 이미지로 우회
          customImage:  unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode-TestResults
          path: artifacts

  # 2) Windows Standalone 빌드 (같은 이미지 사용)
  build:
    name: Build Windows
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Build Windows Standalone
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion:    2022.3.26f1
          targetPlatform:  StandaloneWindows64
          customImage:     unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/Windows
