# .github/workflows/unity-ci.yml
name: Unity CI (2022.3.26f1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1) 라이선스 활성화
  activate:
    name: Activate Unity License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - id: activate
        name: Activate License (GameCI)
        uses: game-ci/unity-activate@v2.0.0
        with:
          unityVersion: 2022.3.26f1
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  # 2) PlayMode 테스트 (Windows‑Mono Docker 이미지 사용)
  test:
    name: PlayMode Tests
    runs-on: ubuntu-latest
    needs: activate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Run PlayMode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath:  .
          unityVersion: 2022.3.26f1
          githubToken:  ${{ secrets.GITHUB_TOKEN }}
          testMode:     playmode
          customImage:  unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode-TestResults
          path: artifacts

  # 3) Standalone Windows 빌드
  build:
    name: Build Windows
    runs-on: ubuntu-latest
    needs: activate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Build Windows Standalone
        uses: game-ci/unity-builder@v4
        with:
          unityVersion:    2022.3.26f1
          targetPlatform:  StandaloneWindows64
          customImage:     unityci/editor:ubuntu-2022.3.26f1-windows-mono-3.0.1
        env:
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/Windows
